README.md
Maybe let's not frighten out the folk with counting React for math =)
=> Fiddling with secitons

README.md
This is a Rust Ethereum library I've been maintaining, in case you want to include it in the docs :)
=> docs: add ethers-rs

README.md
[Starport](https://github.com/tendermint/starport) is an easy-to-use CLI tool for creating sovereign application-specific blockchains. Blockchains created with Starport use Cosmos SDK and Tendermint. Starport and the Cosmos SDK modules are written in the Go programming language.
Website: https://cosmos.network/starport
Documentation: https://docs.starport.network
Github: https://github.com/tendermint/starport
=> Add Starport CLI to the Frameworks section

translations/README_ko.md
Hello, OffcierCia!
I learned about this place while studying because I wanted to be a developer of DeFi.
I hope it will be of great help to Koreans who want to be blockchain and DeFi developers like me.
If I have time, I will continue to contribute to Korean translation work!
Thank you for writing a good article.
=> Added the translations for the Korean language

translations/README_ko.md
Hello, OffcierCia!
Added the all translations for the Korean language!
=> Added the all translations for the Korean language

README.md
=> Added brave-ui

README.md
add some additional useful utilities. Also add a notice on some tools that are no longer being updated
=> docs(readme): add tooling and depreciation notices

README.md
Add Watchdata to Test Blockchain Networks, Ethereum Clients
=> Add Watchdata to Test Blockchain Networks, Ethereum Clients

README.md
Just added the [Foundry Book to the frameworks categories](https://onbjerg.github.io/foundry-book/getting-started/index.html) 😉
=> feat: add foundry to other frameworks

README.md
Added a few cybersecurity resources for developers to learn about the most common Web2 vulnerabilities
=> feat: add cybersecurity training resources

README.md
Included a few resources for developers to hone in their cybersecurity skills
=> feat: add web3 cybersecurity resources

README.md
Preethi Kasireddy's article was removed from Medium and added to the personal website.
New: https://www.preethikasireddy.com/post/how-does-ethereum-work-anyway#:~:text=The%20Ethereum%20blockchain%20uses%20an,tokens%20are%20generated%20and%20awarded.
Old: https://medium.com/@preethikasireddy/how-does-ethereum-work-anyway-22d1df506369
=> Update Link to How does Ethereum work, anyway?

README.md
A nice dApp scaffold for Svelte devs
=> added Jolly Roger

translations/README_ko.md
- Make a sentence naturally
- Fix spelling
=> (ko) Make a sentence naturally & Fix spelling

translations/README_fr.md
=> French README

translations/README-fa.md
=> Update and rename README.md to translations/README-fa.md

translations/README_cn.md
=> add db3 network_cn

README.md
Add "Supercool" to the "Other Frameworks" section. Supercool is backend infra to automate transaction creation and enable meta-transaction and account abstraction transaction capabilities.
Disclaimer: I am a co-founder of Supercool, but wanted to share. We're developers and built the relayer and transaction infra we wish we had when working on other projects.
=> Add "Supercool" to the frameworks section

README.md
little fix: made description shorter
=> Update README.md (little fix of description)

README.md
Request to add [dAppling Network](https://dappling.network) - a decentralized web hosting platform for Web3 frontends that uses IPFS
Thanks for reviewing :)
=> add dappling network

translations/README_yor.md
This Pull requests adds a yoruba translation of the readme.md to this repo
=> Added Readme Yoruba translation
